deploy:
  image: gradle:8.7-jdk21-alpine
  script:
    - 'chmod +x ./gradlew'
    - './gradlew :generator-base:clean :generator-base:publishMavenPublicationToGitLabRepository'
    - './gradlew clean publishPluginMavenPublicationToGitLabRepository'
  only:
    - tags