deploy:
  image: gradle:8.0.1-jdk17-alpine
  script:
    - 'gradle :generator-base:clean :generator-base:publishMavenPublicationToGitLabRepository'
    - 'gradle clean publishPluginMavenPublicationToGitLabRepository'
  only:
    - tags